### PR TITLE
449/created VMs in wrong network

### LINKED ISSUE #449: created VMs in wrong vsphere network
Beim automatischen Erstellen von VMs wird die NIC der Maschine im Netzwerk 'VM Network' eingerichtet. Da dieses Netzwerk nicht existiert, wird es automatisch von vSphere erstellt. Es gibt aber ein Standard Netzwerk, in welchem alle VMs erstellt werden sollen.
Die vSphere API sollte eine Liste zurückliefern und das oberste Element ausgewählt werden. Ansonsten funktioniert das automatische Deployment und der pxeboot nicht.

### PR DESCRIPTION
**Pull request by MrModder**
Closes #449

### CODE REVIEW

File: app/models/request.rb [hunk 1]
```diff
@@ -84,27 +84,33 @@ def create_vm
...
+      description: description
+    )
     vm.move_into_correct_subfolder
     vm
   end
 
-  # Error handling has been moved into create_vm to provide easier feedback for the user
+  def push_to_git_with_warnings
+    push_to_git
+    nil
```
Comment (BjoernDaase) [inline app/models/request.rb]: I don't understand this nil here. Can you explain me what it does?

Comment (MrModder) [reply app/models/request.rb]: if everything works, return nil as warning

Comment (MrModder) [reply app/models/request.rb]: nil here means, there was no warning
