### PR TITLE
Fix bug concerning reboot and shutdown of guests

### LINKED ISSUE #421: VM restart triggers rails error
**Summary**

[//]: # (Please provide a details description about the issue you are facing.)
When I try to restart a VM via manage -> restart Guest OS  a rails error is shown. Open-vm-tools are installed. VM OS is Ubuntu 18.04.
VM is restarted anyway.

**Steps to Reproduce**

[//]: # (Please provide the steps to reproduce the defect. Try to be as specific as possible in order to avoid ambigious testing.)

1. click on VM's details page manage
1. click restart Guest-OS

**Actual Results**

[//]: # (Describe the results you've got.)

**Expected Results**

[//]: # (Describe the results you've expected.)

**Annex**

[//]: # (Please provide screenshots or screencasts if applicable.)
2019_02_26_15_27_39_window

### PR DESCRIPTION
**Pull request by BraunTom**
Fixes #421 

RebootGuest and ShutdownGuest do not have a return value.
See:
- https://code.vmware.com/apis/196/vsphere#/doc/vim.VirtualMachine.html#rebootGuest
- https://code.vmware.com/apis/196/vsphere#/doc/vim.VirtualMachine.html#shutdownGuest

### CODE REVIEW

File: app/api/v_sphere/virtual_machine.rb [hunk 1]
```diff
@@ -111,11 +111,15 @@ def reset_vm
...
+      # Do not `wait_for_completion` here, as `ShutdownGuest` does not offer a useful return value
+      # https://code.vmware.com/apis/196/vsphere#/doc/vim.VirtualMachine.html#shutdownGuest
+      @vm.ShutdownGuest if powered_on?
     end
 
     def reboot_guest_os
-      @vm.RebootGuest.wait_for_completion
+      # Do not `wait_for_completion` here, as `RebootGuest` does not offer a useful return value
+      # https://code.vmware.com/apis/196/vsphere#/doc/vim.VirtualMachine.html#rebootGuest
+      @vm.RebootGuest
```
Comment (chrisma) [inline app/api/v_sphere/virtual_machine.rb]: Does this need `if powered_on?`? Can a guest be rebooted if it is powered off?

Comment (BjoernDaase) [reply app/api/v_sphere/virtual_machine.rb]: No, it can't. See:
screenshot from 2019-03-05 12-43-03

Comment (chrisma) [reply app/api/v_sphere/virtual_machine.rb]: Thanks for the info! Should the `if powered_on?` condition be added here then?

Comment (BjoernDaase) [reply app/api/v_sphere/virtual_machine.rb]: @BraunTom Is there a reason it isn't here?

Comment (BjoernDaase) [reply app/api/v_sphere/virtual_machine.rb]: @chrisma Fixed in https://github.com/hpi-swt2/vm-portal/pull/442/commits/6601a7324719579d0107cf2009e40f04840d5f8a.
